### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by Flaviu8**
i removed join button from navbar

### CODE REVIEW

**Review by Flaviu8 — COMMENTED** [review]
...

**Comment by sgarciahelguera** [comment]
can you confirm the only relevant changes for this are on this file : src/components/Navbar/navbar.module.scss

**Comment by sgarciahelguera** [comment]
sorry but I am having a hard time navigating this pr for some reason, I think it is because there are many files

**Review by sgarciahelguera — APPROVED** [review]
Looks good

**Pull request merged**
