### PR TITLE
New branch

### PR DESCRIPTION
**Pull request by Flaviu8**

### CODE REVIEW

**Comment by sgarciahelguera** [comment]
You need to resolve the conflicts.
You can add a reviewer on the right pane to request review from someone (so that you don't need to do it through discord, not that it is wrong to ask there anyway).
You should name your branch and PR with something indicative of what you are doing and add a description that helps the reviewer understand what you are trying to do.

**Comment by sgarciahelguera** [comment]
As most the conflicting files are under a folder named cache, I am guessing that they should be deleted

**Comment by Flaviu8** [comment]
i remove join button  from navbar

**Comment by sgarciahelguera** [comment]
You should update your branch from main 
It is strange that it is out of date , maybe you are missing the last merge?

**Pull request closed without merging**
